name: Build and Push Docker Containers

on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build & Push (py39-anaconda-2022-10-jb-0.12.1)
      #   uses: docker/build-push-action@v3.2.0
      #   with:
      #     context: py39-anaconda-2022-10-jb-0.12.1
      #     push: true
      #     tags: mmcky/quantecon-lecture-python:py39-anaconda-2022-10-jb-0.12.1

      # - name: Build & Push (py39-anaconda-2022-10-jb-0.15.1)
      #   uses: docker/build-push-action@v3.2.0
      #   with:
      #     context: py39-anaconda-2022-10-jb-0.15.1
      #     push: true
      #     tags: mmcky/quantecon-lecture-python:py39-anaconda-2022-10-jb-0.15.1
      
      - name: Build & Push (py310-anaconda-2023-03-jb-0.15.1)
        uses: docker/build-push-action@v3.2.0
        with:
          context: py310-anaconda-2023-03-jb-0.15.1
          push: true
          tags: mmcky/quantecon-lecture-python:py310-anaconda-2023-03-jb-0.15.1